############################## INSTRUCTIONS ##########################
# 1. Replace wifi credentials with your own
# 2. Replace the OTA password with your own
# 3. Replace the sample API key with your own base64 encoded password
######################################################################

# Your Wi-Fi SSID and password
wifi_ssid: "WIFI_SSID_HERE"
wifi_password: "WIFI_PASSWORD_HERE"

# OTA Password
ota_password: "OTA_PASSWORD_HERE"

# API Key
api_encryption_key: "4tUuxtHhCRd6087z4WDKTW4N54rvClTExCwOgjxOPKA="
