############################## INSTRUCTIONS ##########################
# 1. Replace wifi credentials with your own
# 2. Replace the OTA password with your own
# 3. Replace the sample API key with your own base64 encoded password
#
#                     Version: 1.0 | 11/01/2024                      #
######################################################################

# Your Wi-Fi SSID and password
wifi_ssid: "WIFI_SSID_HERE"
wifi_password: "WIFI_PASSWORD_HERE"

# OTA Password
ota_password: "OTA_PASSWORD_HERE"

# API Key
api_encryption_key: "BASE64_ENCODED_KEY_HERE_32BYTE_LENGTH"
